### ISSUE TITLE
bug?: typescript fails to compile angular services, duplicate exports

### ISSUE THREAD

**Issue by dennisroche** [anymaniax/orval#432]
## What are the steps to reproduce this issue?

Attempting to update a project from `orval@6.3.0` to latest generated compile errors. Found last working version `orval@6.6.4`.

1. Using `orval@6.7.0` or later, typescript fails to compile with a previously working schema.

2. Using `orval.config.ts`

   ```ts
   output: {
      mode: 'tags-split',
      workspace: 'src/api/sample-api',
      target: './sample-api.ts',
      client: 'angular',
      ...
   }
   ```

   **N.B** `angular` client

3. Run `orval --config orval.config.ts` to build

## What happens?

Duplicate exports in each generated `*.service.ts` regardless of the the endpoints defined

- In `a.service.ts`

    ```ts
    export type GetValuesAllClientResult = NonNullable<void>;
    export type PostValuesClientResult = NonNullable<void>;
    export type GetValuesClientResult = NonNullable<void>;
    export type PutValuesClientResult = NonNullable<void>;
    export type DeleteValuesClientResult = NonNullable<void>;
    ```

- In `b.service.ts`

    ```ts
    export type GetValuesAllClientResult = NonNullable<void>;
    export type PostValuesClientResult = NonNullable<void>;
    export type GetValuesClientResult = NonNullable<void>;
    export type PutValuesClientResult = NonNullable<void>;
    export type DeleteValuesClientResult = NonNullable<void>;
    ```

## What were you expecting to happen?

Compile successfully.

## Any logs, error output, etc?

Typescript fails to compile with several similar errors. It appears `orval` is exporting all 

```
Error: src/api/sample-api/index.ts:3:1 - error TS2308: Module './debug/debug.service' has already exported a member named 'ValuesPutClientResult'. Consider explicitly re-exporting to resolve the ambiguity.

export * from './values/values.service';.
```

In this case, `./debug/debug.service` is just the first service generated.

## Any other comments?

Compiles with `orval@6.6.4`

## What versions are you using?

**Operating System:** Windows 11
**Package Version:** 6.7.1+
**Browser Version:** N/A

**Comment by maartencardinaels** [comment]
we found out that the culprit is [here](https://github.com/anymaniax/orval/blob/6dbaa3fd604bdc86371a20e1948ca0b3a97c64bb/src/core/generators/angular.ts#L137),    `returnTypesToWrite` is not cleared in between generations and accumulating the previous ones

**Comment by anymaniax** [comment]
Thanks will look into it

**Comment by dennisroche** [comment]
thanks @maartencardinaels for finding the root cause

**Comment by maartencardinaels** [comment]
It also seems that based on the mode, the bug behaving differently. 

For `split` mode you get an accumulation of the types (every next service file contains also the previous ones), while for `tags-split`, you get all the types as duplicates for all service files (line @dennisroche) described above

**Comment by anymaniax** [comment]
fixed will be in the next release

**Comment by anymaniax** [comment]
Released with 6.9.0
