### PR TITLE
fix(msw): generated mocks for polymorphic type

### LINKED ISSUE #555: Syntax error in generated MSW when API returns polymorphic type
## What are the steps to reproduce this issue?

1. Use the following OpenAPI specification as input
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "API",
    "version": "V1"
  },
  "paths": {
    "/flags": {
      "get": {
        "summary": "Get all flags.",
        "description": "Get all flags.",
        "operationId": "getFlags",
        "responses": {
          "200": {
            "description": "A list of flags with details including key, value and data type",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "$ref": "#/components/schemas/BooleanFlag"
                      },
                      {
                        "$ref": "#/components/schemas/JsonFlag"
                      },
                      {
                        "$ref": "#/components/schemas/NullFlag"
                      },
                      {
                        "$ref": "#/components/schemas/NumberFlag"
                      },
                      {
                        "$ref": "#/components/schemas/StringFlag"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "BooleanFlag": {
        "required": [
          "key",
          "type",
          "value"
        ],
        "type": "object",
        "description": "Represent a feature flag with a boolean value.",
        "allOf": [
          {
            "$ref": "#/components/schemas/FlagDetails"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "boolean"
              }
            }
          }
        ]
      },
      "FlagDetails": {
        "required": [
          "key",
          "type",
          "value"
        ],
        "type": "object",
        "properties": {
          "value": {
            "type": "object"
          },
          "key": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "BOOLEAN",
              "STRING",
              "NUMBER",
              "JSON",
              "NULL"
            ]
          }
        },
        "discriminator": {
          "propertyName": "type"
        }
      },
      "JsonFlag": {
        "required": [
          "key",
          "type",
          "value"
        ],
        "type": "object",
        "description": "Represent a feature flag with a raw JSON value.",
        "allOf": [
          {
            "$ref": "#/components/schemas/FlagDetails"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "string"
              }
            }
          }
        ]
      },
      "NullFlag": {
        "required": [
          "key",
          "type",
          "value"
        ],
        "type": "object",
        "description": "Represent a feature flag with no value.",
        "allOf": [
          {
            "$ref": "#/components/schemas/FlagDetails"
          }
        ]
      },
      "NumberFlag": {
        "required": [
          "key",
          "type",
          "value"
        ],
        "type": "object",
        "description": "Represent a feature flag with numeric value.",
        "allOf": [
          {
            "$ref": "#/components/schemas/FlagDetails"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "number"
              }
            }
          }
        ]
      },
      "StringFlag": {
        "required": [
          "key",
          "type",
          "value"
        ],
        "type": "object",
        "description": "Represent a feature flag with string value.",
        "allOf": [
          {
            "$ref": "#/components/schemas/FlagDetails"
          },
          {
            "type": "object",
            "properties": {
              "value": {
                "type": "string"
              }
            }
          }
        ]
      }
    }
  }
}
```
2. Configure Orval to generate mocks (`output.mock: true`)
3. Run Orval

## What happens?

As of version 6.9.X, the mock generator function is missing curly braces around the object declaration, making the generated statement invalid
```typescript
export const getGetFlagsMock = () => (Array.from({ length: faker.datatype.number({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.helpers.arrayElement([value: {}, key: faker.random.word(), type: faker.helpers.arrayElement(['BOOLEAN','STRING','NUMBER','JSON','NULL']),,value: {}, key: faker.random.word(), type: faker.helpers.arrayElement(['BOOLEAN','STRING','NUMBER','JSON','NULL']),,value: {}, key: faker.random.word(), type: faker.helpers.arrayElement(['BOOLEAN','STRING','NUMBER','JSON','NULL']),value: {}, key: faker.random.word(), type: faker.helpers.arrayElement(['BOOLEAN','STRING','NUMBER','JSON','NULL']),,value: {}, key: faker.random.word(), type: faker.helpers.arrayElement(['BOOLEAN','STRING','NUMBER','JSON','NULL']),]))))
```

## What were you expecting to happen?

In versions before 6.9.X, the generator function was correct
```typescript
export const getGetFlagsMock = () =>
  [...Array(faker.datatype.number({ min: 1, max: 10 }))].map(() =>
    faker.random.arrayElement([
      {
        value: {},
        key: faker.random.word(),
        type: faker.random.arrayElement([
          'BOOLEAN',
          'STRING',
          'NUMBER',
          'JSON',
          'NULL',
        ]),
      },
      {
        value: {},
        key: faker.random.word(),
        type: faker.random.arrayElement([
          'BOOLEAN',
          'STRING',
          'NUMBER',
          'JSON',
          'NULL',
        ]),
      },
      {
        value: {},
        key: faker.random.word(),
        type: faker.random.arrayElement([
          'BOOLEAN',
          'STRING',
          'NUMBER',
          'JSON',
          'NULL',
        ]),
      },
      {
        value: {},
        key: faker.random.word(),
        type: faker.random.arrayElement([
          'BOOLEAN',
          'STRING',
          'NUMBER',
          'JSON',
          'NULL',
        ]),
      },
      {
        value: {},
        key: faker.random.word(),
        type: faker.random.arrayElement([
          'BOOLEAN',
          'STRING',
          'NUMBER',
          'JSON',
          'NULL',
        ]),
      },
    ]),);
```

## Any logs, error output, etc?

```sh
> orval --clean && echo 'Running ESLint on generated files, this may take a moment...' && eslint --config .eslintrc.js src/generated/ --fix

🍻 Start orval v6.9.6 - A swagger client generator for typescript
api: Cleaning output folder
🎉 api - Your OpenAPI spec has been converted into ready to use orval!
Running ESLint on generated files, this may take a moment...

/.../src/generated/api/default/default.msw.ts
  14:166  error  Parsing error: ',' expected

✖ 1 problem (1 error, 0 warnings)

```
```txt
/.../src/generated/api/default/default.msw.ts
Error:(14, 162) TS2304: Cannot find name 'value'.
Error:(14, 173) TS2304: Cannot find name 'key'.
Error:(14, 199) TS2304: Cannot find name 'type'.
Error:(14, 278) TS2304: Cannot find name 'value'.
Error:(14, 289) TS2304: Cannot find name 'key'.
Error:(14, 315) TS2304: Cannot find name 'type'.
Error:(14, 394) TS2304: Cannot find name 'value'.
Error:(14, 405) TS2304: Cannot find name 'key'.
Error:(14, 431) TS2304: Cannot find name 'type'.
Error:(14, 509) TS2304: Cannot find name 'value'.
Error:(14, 520) TS2304: Cannot find name 'key'.
Error:(14, 546) TS2304: Cannot find name 'type'.
Error:(14, 625) TS2304: Cannot find name 'value'.
Error:(14, 636) TS2304: Cannot find name 'key'.
Error:(14, 662) TS2304: Cannot find name 'type'.
Error:(14, 167) TS1005: ',' expected.
Error:(14, 176) TS1005: ',' expected.
Error:(14, 203) TS1005: ',' expected.
Error:(14, 283) TS1005: ',' expected.
Error:(14, 292) TS1005: ',' expected.
Error:(14, 319) TS1005: ',' expected.
Error:(14, 399) TS1005: ',' expected.
Error:(14, 408) TS1005: ',' expected.
Error:(14, 435) TS1005: ',' expected.
Error:(14, 514) TS1005: ',' expected.
Error:(14, 523) TS1005: ',' expected.
Error:(14, 550) TS1005: ',' expected.
Error:(14, 630) TS1005: ',' expected.
Error:(14, 639) TS1005: ',' expected.
Error:(14, 666) TS1005: ',' expected.
```

## Any other comments?
N/A

## What versions are you using?

**Operating System:** Arch Linux 5.19.3-arch1-1
**Package Version:** Orval: 6.9.6, msw: 0.45.0
**Browser Version:** Firefox 103.0.2 (64-bit)

### PR DESCRIPTION
**Pull request by DominicBach**
## Status

**WIP**

## Description

Fixes #555 - When a response contains a polymorphic type, the generated mock object code was missing curly braces. This error was introduced in https://github.com/anymaniax/orval/commit/899a8cbd4c93190bd01ebd5e36be81d750b7608f.
Previously, when calling `resolveMockValue` within a `oneOf`, the `combine` option was undefined. The change resulted in the option being defined, resulting in a failing check for object boundaries.

This fix adds a check for `combine.separator === 'oneOf'` when determining object boundaries.

## Todos

- [x] Tests
- [ ] Documentation - N/A
- [ ] Changelog Entry (unreleased)  - N/A

## Steps to Test or Reproduce

1. Added a sample YAML swagger definition to tests (polymorphic.yaml)
2. Added the sample case to the test react-query.config.ts

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Review by anymaniax — APPROVED** [review]
Seems great thanks!

**Comment by DominicBach** [comment]
Ah, I didn't actually look into how the tests were being run :facepalm:
I can "fix" it by changing the condition to `const isObjectBounds = !combine || (combine.separator == 'oneOf' && separator == 'allOf');`, but at that point it's just fixing my specific use-case and I don't know if it's a proper solution.

**Comment by DominicBach** [comment]
I have to close this PR and reopen a new one because it's no longer synched with my fork...
